version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "test"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "test"
    ignore:
      - dependency-name: "torch"
      - dependency-name: "torchvision"
      - dependency-name: "transformers"
        versions: [">= 5.0.0"]
