name: Docker Build & Publish

on:
  push:
    branches: [test, master]
    tags: ['v*']
  pull_request:
    branches: [test, master]
  release:
    types: [published]

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ufal/atrium-project/.github/workflows/docker-tool.reusable.yml@main
    secrets: inherit
    with:
      image-name: ufal/atrium-translator
      requirements: requirements.txt service/requirements.txt requirements-test.txt