name: Build and Test Docker Image

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-publish:
    uses: ufal/atrium-project/.github/workflows/docker-tool.reusable.yml@main
    with:
      image-name: "atrium-translator"
      pre-install-torch: true
    secrets: inherit