name: Build and Push Docker Image

on:
  push:
    branches: [test, master]
    tags: ['v*']
  pull_request:
    branches: [test, master]

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    # Using the @test branch since the upstream templates are not on main yet
    uses: ufal/atrium-project/.github/workflows/docker-tool.reusable.yml@test
    secrets: inherit
    with:
      image-name: ufal/atrium-translator
      requirements: requirements.txt requirements-test.txt
