name: Security Scans

on:
  push:
    branches: [ test, master ]
  pull_request:
    branches: [ test, master ]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  trivy-scan:
    uses: ufal/atrium-project/.github/workflows/security.reusable.yml@test
    with:
      image-ref: ghcr.io/ufal/atrium-translator:latest
