name: Security Scan

on:
  push:
    branches: [test, master]
  pull_request:
    branches: [test, master]

jobs:
  security-scan:
    permissions:
      contents: read
      packages: read
      security-events: write
    uses: ufal/atrium-project/.github/workflows/security.reusable.yml@test
    secrets: inherit
    with:
      image-ref: ghcr.io/ufal/atrium-translator:latest
      citation-path: CITATION.cff
      para-config-path: para_config.txt
